# Generated by Django 4.2.7 on 2023-12-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carShowRoom', '0006_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='color',
        ),
    ]
