# Generated by Django 4.2.7 on 2023-12-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carShowRoom', '0008_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='password',
        ),
    ]
