# Generated by Django 4.2.7 on 2023-12-16 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carShowRoom', '0009_rename_email_user_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
