# Generated by Django 4.2.7 on 2023-12-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carShowRoom', '0010_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
