# Generated by Django 4.2.7 on 2023-12-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carShowRoom', '0012_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
