# Generated by Django 4.2.7 on 2023-12-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carShowRoom', '0016_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
