# Generated by Django 4.2.7 on 2023-12-20 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carShowRoom', '0019_cardashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardashboard',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carShowRoom.carcolor'),
        ),
    ]
