# Generated by Django 4.2.7 on 2023-12-20 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carShowRoom', '0020_cardashboard_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardashboard',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carShowRoom.color'),
        ),
    ]
