# Generated by Django 4.2.7 on 2023-12-20 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carShowRoom', '0021_alter_cardashboard_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='payment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
