# Generated by Django 4.2.7 on 2023-12-24 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carShowRoom', '0022_system_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='car_videos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carShowRoom.car')),
            ],
        ),
    ]
