# Generated by Django 4.2.7 on 2023-12-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carShowRoom', '0024_like_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
