# Generated by Django 4.2.7 on 2024-01-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carShowRoom', '0026_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
